#!/usr/bin/env bash
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NIXOS_DIR="/etc/nixos"
TS="$(date +%Y%m%d-%H%M%S)"
BACKUP_DIR="/etc/nixos.backup-$TS"
TRASH_DIR="$HOME/.config/rice-removed-$TS"
DO_SWITCH=1

usage() {
    cat <<EOF
Usage: ./install.sh [--no-switch]

Copies this rice into $NIXOS_DIR (with a backup), removes the replaced
modules, then runs
  sudo nixos-rebuild dry-build --flake $NIXOS_DIR#nixos
and (unless --no-switch) finishes with
  sudo nixos-rebuild switch --flake $NIXOS_DIR#nixos
(matugen output files are bootstrapped by home.activation during switch)

Options:
  --no-switch   Stop after the dry build (nothing is activated)
  -h, --help    Show this help
EOF
}

while [ $# -gt 0 ]; do
    case "$1" in
        --no-switch) DO_SWITCH=0 ;;
        -h|--help) usage; exit 0 ;;
        *) echo "Unknown option: $1" >&2; usage >&2; exit 1 ;;
    esac
    shift
done

DELETE_FILES=(
    hm-modules/waybar.nix
    hm-modules/wofi.nix
    hm-modules/hyprlock.nix
)

echo "==> Pre-flight checks"
[ -d "$NIXOS_DIR" ] || { echo "ERROR: $NIXOS_DIR not found" >&2; exit 1; }
command -v nix >/dev/null || { echo "ERROR: nix not found" >&2; exit 1; }
[ -e "$REPO/vars.nix" ] || { echo "ERROR: vars.nix missing — run ./configure.sh first, or copy vars.example.nix to vars.nix and fill it in" >&2; exit 1; }

echo "==> Backing up $NIXOS_DIR -> $BACKUP_DIR"
sudo cp -a "$NIXOS_DIR" "$BACKUP_DIR"
echo "    (restore with: sudo cp -a $BACKUP_DIR/. $NIXOS_DIR/ )"

echo "==> Copying rice tree into $NIXOS_DIR"
sudo rm -rf "$NIXOS_DIR/gtk-css" "$NIXOS_DIR/icons"
sudo rsync -a \
  --exclude='.git' --exclude='result' --exclude='result-*' --exclude='.direnv' \
  --exclude='configure.sh' --exclude='install.sh' --exclude='README.md' \
  --exclude='LICENSE' --exclude='.editorconfig' --exclude='vars.example.nix' \
  "$REPO"/ "$NIXOS_DIR"/

echo "==> Removing replaced modules"
for f in "${DELETE_FILES[@]}"; do
    sudo rm -f "$NIXOS_DIR/$f"
    echo "    removed $NIXOS_DIR/$f"
done

echo "==> Matugen outputs are bootstrapped by home.activation during switch"
echo "    (hyprland/kitty/fuzzel/btop/zathura + starship/hyprlock/qt6ct colors"
echo "     are created from your current wallpaper if missing)"

echo "==> Pointing btop at the matugen theme"
if [ -f "$HOME/.config/btop/btop.conf" ]; then
    if grep -q '^color_theme' "$HOME/.config/btop/btop.conf"; then
        sed -i 's/^color_theme.*/color_theme = "matugen"/' "$HOME/.config/btop/btop.conf"
    else
        printf '\ncolor_theme = "matugen"\n' >> "$HOME/.config/btop/btop.conf"
    fi
    echo "    btop color_theme = matugen"
else
    echo "    (no btop.conf yet - create one with: color_theme = \"matugen\")"
fi

echo "==> Removing Hyprland's auto-generated config stub (blocks Home Manager)"
if [ -f "$HOME/.config/hypr/hyprland.conf" ] && grep -q "This config is a STUB" "$HOME/.config/hypr/hyprland.conf" 2>/dev/null; then
    rm -f "$HOME/.config/hypr/hyprland.conf"
    echo "    removed autogenerated ~/.config/hypr/hyprland.conf stub"
fi

echo "==> Moving stale unmanaged configs out of the way"
mkdir -p "$TRASH_DIR"
for d in waybar wofi; do
    if [ -e "$HOME/.config/$d" ]; then
        mv "$HOME/.config/$d" "$TRASH_DIR/$d"
        echo "    moved ~/.config/$d -> $TRASH_DIR/$d"
    fi
done

echo "==> Locking flake inputs (adds caelestia-shell)"
sudo nix flake lock "$NIXOS_DIR"

echo "==> Removing generated GTK theme files so Home Manager can own them"
rm -f "$HOME/.config/gtk-3.0/gtk.css" "$HOME/.config/gtk-3.0/thunar.css" \
      "$HOME/.config/gtk-4.0/gtk.css" "$HOME/.config/gtk-4.0/thunar.css" \
      "$HOME/.config/caelestia/cli.json" \
      "$HOME/.config/qt6ct/qt6ct.conf"

echo "==> Fixing the PrismLauncher local desktop icon (tilde not expanded)"
if [ -f "$HOME/.local/share/applications/prismlauncher.desktop" ]; then
    sed -i 's|^Icon=.*|Icon=org.prismlauncher.PrismLauncher|' "$HOME/.local/share/applications/prismlauncher.desktop"
fi

echo "==> Dry build (catches evaluation/build errors, activates nothing)"
sudo nixos-rebuild dry-build --flake "$NIXOS_DIR#nixos"

if [ "$DO_SWITCH" -eq 1 ]; then
    echo "==> Testing (switches into new config WITHOUT touching /boot)"
    sudo nixos-rebuild test --flake "$NIXOS_DIR#nixos"

    echo "==> Switching to the new configuration (updates /boot)"
    sudo nixos-rebuild switch --flake "$NIXOS_DIR#nixos"

    echo "==> Applying matugen colors for the current wallpaper"
    if [ -f "$HOME/.cache/current-wallpaper.jpg" ] && command -v matugen >/dev/null 2>&1; then
        MT="scheme-tonal-spot"
        MD="dark"
        if [ -f "$HOME/.cache/matugen-state" ]; then
            read -r MT MD < "$HOME/.cache/matugen-state" || true
        fi
        MT="${MT:-scheme-tonal-spot}"
        MD="${MD:-dark}"
        matugen image "$HOME/.cache/current-wallpaper.jpg" -t "$MT" -m "$MD" --source-color-index 0 || true
    fi
else
    echo "==> --no-switch: dry build passed, nothing activated"
fi

cat <<EOF

Done. Next steps:
  1. Log out and back in (caelestia shell, plugin binds, SDDM cursor).
  2. Reboot once to see the new plymouth splash.
  3. Read README.md (Rice notes) for what changed (keybinds, removed apps).

Backup:  $BACKUP_DIR
Moved:   $TRASH_DIR
EOF
