# Self-contained purge package: embeds all .rs sources + Cargo.toml/Cargo.lock,
# builds with rustPlatform.buildRustPackage (pinned cargo lock), and wraps only
# `npm` (nodejs) into PATH -- every other binary purge execs already ships on a
# stock NixOS (coreutils, findutils, util-linux, systemd, nix, sudo).
{
  lib,
  rustPlatform,
  stdenv,
  makeWrapper,
  nodejs,
}:

let
  cargoToml = builtins.toFile "Cargo.toml" ''
    [package]
    name = "purge"
    version = "0.1.0"
    edition = "2021"
    description = "Catppuccin-themed RAM and storage cleaning TUI for NixOS"

    [dependencies]
    ratatui = "0.29"
    crossterm = "0.28"

    [profile.release]
    lto = true
    strip = true
  '';
  cargoLock = builtins.toFile "Cargo.lock" ''
    # This file is automatically @generated by Cargo.
    # It is not intended for manual editing.
    version = 4

    [[package]]
    name = "allocator-api2"
    version = "0.2.21"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "683d7910e743518b0e34f1186f92494becacb047c7b6bf616c96772180fef923"

    [[package]]
    name = "bitflags"
    version = "2.13.1"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "b588b76d00fde79687d7646a9b5bdf3cc0f655e0bbd080335a95d7e96f3587da"

    [[package]]
    name = "cassowary"
    version = "0.3.0"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "df8670b8c7b9dae1793364eafadf7239c40d669904660c5960d74cfd80b46a53"

    [[package]]
    name = "castaway"
    version = "0.2.4"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "dec551ab6e7578819132c713a93c022a05d60159dc86e7a7050223577484c55a"
    dependencies = [
     "rustversion",
    ]

    [[package]]
    name = "cfg-if"
    version = "1.0.4"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "9330f8b2ff13f34540b44e946ef35111825727b38d33286ef986142615121801"

    [[package]]
    name = "compact_str"
    version = "0.8.2"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "7fd622ebbb56a5b2ccb651b32b911cdeb2a9b4b11776b2473bf26a26a286244e"
    dependencies = [
     "castaway",
     "cfg-if",
     "itoa",
     "rustversion",
     "ryu",
     "static_assertions",
    ]

    [[package]]
    name = "crossterm"
    version = "0.28.1"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "829d955a0bb380ef178a640b91779e3987da38c9aea133b20614cfed8cdea9c6"
    dependencies = [
     "bitflags",
     "crossterm_winapi",
     "mio",
     "parking_lot",
     "rustix",
     "signal-hook",
     "signal-hook-mio",
     "winapi",
    ]

    [[package]]
    name = "crossterm_winapi"
    version = "0.9.1"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "acdd7c62a3665c7f6830a51635d9ac9b23ed385797f70a83bb8bafe9c572ab2b"
    dependencies = [
     "winapi",
    ]

    [[package]]
    name = "darling"
    version = "0.24.0"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "88490bf1b990d87eaaa7ac8aa887f629a08e7359765b4911faf63c3763347d23"
    dependencies = [
     "darling_core",
     "darling_macro",
    ]

    [[package]]
    name = "darling_core"
    version = "0.24.0"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "084e274f91c482280130e1e34e0b8d6e66776a060d7b6de7b84289ca778868c4"
    dependencies = [
     "ident_case",
     "proc-macro2",
     "quote",
     "strsim",
     "syn 3.0.3",
    ]

    [[package]]
    name = "darling_macro"
    version = "0.24.0"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "68f5792fa0d41cd2325ce0ffa64f0a340eaebd4971a3a0c5e1ffd2cc488a355e"
    dependencies = [
     "darling_core",
     "quote",
     "syn 3.0.3",
    ]

    [[package]]
    name = "either"
    version = "1.17.0"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "9e5e8f6c15a24b9a3ee5efec809ccd006d3b30e8b3bb63c39af737c7f87daa1d"

    [[package]]
    name = "equivalent"
    version = "1.0.2"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "877a4ace8713b0bcf2a4e7eec82529c029f1d0619886d18145fea96c3ffe5c0f"

    [[package]]
    name = "errno"
    version = "0.3.14"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "39cab71617ae0d63f51a36d69f866391735b51691dbda63cf6f96d042b63efeb"
    dependencies = [
     "libc",
     "windows-sys 0.61.2",
    ]

    [[package]]
    name = "foldhash"
    version = "0.1.5"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "d9c4f5dac5e15c24eb999c26181a6ca40b39fe946cbe4c263c7209467bc83af2"

    [[package]]
    name = "hashbrown"
    version = "0.15.5"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "9229cfe53dfd69f0609a49f65461bd93001ea1ef889cd5529dd176593f5338a1"
    dependencies = [
     "allocator-api2",
     "equivalent",
     "foldhash",
    ]

    [[package]]
    name = "heck"
    version = "0.5.0"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "2304e00983f87ffb38b55b444b5e3b60a884b5d30c0fca7d82fe33449bbe55ea"

    [[package]]
    name = "ident_case"
    version = "1.0.1"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "b9e0384b61958566e926dc50660321d12159025e767c18e043daf26b70104c39"

    [[package]]
    name = "indoc"
    version = "2.0.7"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "79cf5c93f93228cf8efb3ba362535fb11199ac548a09ce117c9b1adc3030d706"
    dependencies = [
     "rustversion",
    ]

    [[package]]
    name = "instability"
    version = "0.3.13"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "2bf84e73fa6f27f299dec58e13223cf70db80da872eb921d4f6138342a0eabc8"
    dependencies = [
     "darling",
     "indoc",
     "proc-macro2",
     "quote",
     "syn 3.0.3",
    ]

    [[package]]
    name = "itertools"
    version = "0.13.0"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "413ee7dfc52ee1a4949ceeb7dbc8a33f2d6c088194d9f922fb8318faf1f01186"
    dependencies = [
     "either",
    ]

    [[package]]
    name = "itoa"
    version = "1.0.18"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "8f42a60cbdf9a97f5d2305f08a87dc4e09308d1276d28c869c684d7777685682"

    [[package]]
    name = "libc"
    version = "0.2.189"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "3eaf3ede3fee6db1a4c2ee091bf8a8b4dccdc6d17f656fb07896ee72867612f2"

    [[package]]
    name = "linux-raw-sys"
    version = "0.4.15"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "d26c52dbd32dccf2d10cac7725f8eae5296885fb5703b261f7d0a0739ec807ab"

    [[package]]
    name = "lock_api"
    version = "0.4.14"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "224399e74b87b5f3557511d98dff8b14089b3dadafcab6bb93eab67d3aace965"
    dependencies = [
     "scopeguard",
    ]

    [[package]]
    name = "log"
    version = "0.4.33"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "0ceec5bc11778974d1bcb055b18002eba7f4b3518b6a0081b3af5f21666da9ad"

    [[package]]
    name = "lru"
    version = "0.12.5"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "234cf4f4a04dc1f57e24b96cc0cd600cf2af460d4161ac5ecdd0af8e1f3b2a38"
    dependencies = [
     "hashbrown",
    ]

    [[package]]
    name = "mio"
    version = "1.2.2"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "30d65c71f1ce40ab09135ce117d742b9f8a19ff91a41a8b57ed50bc2de59c427"
    dependencies = [
     "libc",
     "log",
     "wasi",
     "windows-sys 0.61.2",
    ]

    [[package]]
    name = "parking_lot"
    version = "0.12.5"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "93857453250e3077bd71ff98b6a65ea6621a19bb0f559a85248955ac12c45a1a"
    dependencies = [
     "lock_api",
     "parking_lot_core",
    ]

    [[package]]
    name = "parking_lot_core"
    version = "0.9.12"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "2621685985a2ebf1c516881c026032ac7deafcda1a2c9b7850dc81e3dfcb64c1"
    dependencies = [
     "cfg-if",
     "libc",
     "redox_syscall",
     "smallvec",
     "windows-link",
    ]

    [[package]]
    name = "paste"
    version = "1.0.15"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "57c0d7b74b563b49d38dae00a0c37d4d6de9b432382b2892f0574ddcae73fd0a"

    [[package]]
    name = "proc-macro2"
    version = "1.0.107"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "985e7ec9bb745e6ce6535b544d84d6cd6f7ad8bd711c398938ae983b91a766d9"
    dependencies = [
     "unicode-ident",
    ]

    [[package]]
    name = "purge"
    version = "0.1.0"
    dependencies = [
     "crossterm",
     "ratatui",
    ]

    [[package]]
    name = "quote"
    version = "1.0.47"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "1fbf4db142a473a8d80c26bbf18454ed458bf8d26c8219c331daecfdbd079001"
    dependencies = [
     "proc-macro2",
    ]

    [[package]]
    name = "ratatui"
    version = "0.29.0"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "eabd94c2f37801c20583fc49dd5cd6b0ba68c716787c2dd6ed18571e1e63117b"
    dependencies = [
     "bitflags",
     "cassowary",
     "compact_str",
     "crossterm",
     "indoc",
     "instability",
     "itertools",
     "lru",
     "paste",
     "strum",
     "unicode-segmentation",
     "unicode-truncate",
     "unicode-width 0.2.0",
    ]

    [[package]]
    name = "redox_syscall"
    version = "0.5.18"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "ed2bf2547551a7053d6fdfafda3f938979645c44812fbfcda098faae3f1a362d"
    dependencies = [
     "bitflags",
    ]

    [[package]]
    name = "rustix"
    version = "0.38.44"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "fdb5bc1ae2baa591800df16c9ca78619bf65c0488b41b96ccec5d11220d8c154"
    dependencies = [
     "bitflags",
     "errno",
     "libc",
     "linux-raw-sys",
     "windows-sys 0.59.0",
    ]

    [[package]]
    name = "rustversion"
    version = "1.0.23"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "cf54715a573b99ac80df0bc206da022bcd442c974952c7b9720069370852e21f"

    [[package]]
    name = "ryu"
    version = "1.0.23"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "9774ba4a74de5f7b1c1451ed6cd5285a32eddb5cccb8cc655a4e50009e06477f"

    [[package]]
    name = "scopeguard"
    version = "1.2.0"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "94143f37725109f92c262ed2cf5e59bce7498c01bcc1502d7b9afe439a4e9f49"

    [[package]]
    name = "signal-hook"
    version = "0.3.18"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "d881a16cf4426aa584979d30bd82cb33429027e42122b169753d6ef1085ed6e2"
    dependencies = [
     "libc",
     "signal-hook-registry",
    ]

    [[package]]
    name = "signal-hook-mio"
    version = "0.2.5"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "b75a19a7a740b25bc7944bdee6172368f988763b744e3d4dfe753f6b4ece40cc"
    dependencies = [
     "libc",
     "mio",
     "signal-hook",
    ]

    [[package]]
    name = "signal-hook-registry"
    version = "1.4.8"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "c4db69cba1110affc0e9f7bcd48bbf87b3f4fc7c61fc9155afd4c469eb3d6c1b"
    dependencies = [
     "errno",
     "libc",
    ]

    [[package]]
    name = "smallvec"
    version = "1.15.2"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "8ed6a63f02c8539c91a8685a86f4099661ba3da017932f6ebbea6de3f0fa7c90"

    [[package]]
    name = "static_assertions"
    version = "1.1.0"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "a2eb9349b6444b326872e140eb1cf5e7c522154d69e7a0ffb0fb81c06b37543f"

    [[package]]
    name = "strsim"
    version = "0.11.1"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "7da8b5736845d9f2fcb837ea5d9e2628564b3b043a70948a3f0b778838c5fb4f"

    [[package]]
    name = "strum"
    version = "0.26.3"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "8fec0f0aef304996cf250b31b5a10dee7980c85da9d759361292b8bca5a18f06"
    dependencies = [
     "strum_macros",
    ]

    [[package]]
    name = "strum_macros"
    version = "0.26.4"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "4c6bee85a5a24955dc440386795aa378cd9cf82acd5f764469152d2270e581be"
    dependencies = [
     "heck",
     "proc-macro2",
     "quote",
     "rustversion",
     "syn 2.0.119",
    ]

    [[package]]
    name = "syn"
    version = "2.0.119"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "872831b642d1a07999a962a351ed35b955ea2cfc8f3862091e2a240a84f17297"
    dependencies = [
     "proc-macro2",
     "quote",
     "unicode-ident",
    ]

    [[package]]
    name = "syn"
    version = "3.0.3"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "53e9bae58849f64dfa4f5d5ae372c8341f7305f82a3868709269343628b659a3"
    dependencies = [
     "proc-macro2",
     "quote",
     "unicode-ident",
    ]

    [[package]]
    name = "unicode-ident"
    version = "1.0.24"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "e6e4313cd5fcd3dad5cafa179702e2b244f760991f45397d14d4ebf38247da75"

    [[package]]
    name = "unicode-segmentation"
    version = "1.13.3"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "c6f5d3c3b1bf09027a88a6bc961fc00497d651009560b5463668dc81b0fa87a8"

    [[package]]
    name = "unicode-truncate"
    version = "1.1.0"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "b3644627a5af5fa321c95b9b235a72fd24cd29c648c2c379431e6628655627bf"
    dependencies = [
     "itertools",
     "unicode-segmentation",
     "unicode-width 0.1.14",
    ]

    [[package]]
    name = "unicode-width"
    version = "0.1.14"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "7dd6e30e90baa6f72411720665d41d89b9a3d039dc45b8faea1ddd07f617f6af"

    [[package]]
    name = "unicode-width"
    version = "0.2.0"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "1fc81956842c57dac11422a97c3b8195a1ff727f06e85c84ed2e8aa277c9a0fd"

    [[package]]
    name = "wasi"
    version = "0.11.1+wasi-snapshot-preview1"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "ccf3ec651a847eb01de73ccad15eb7d99f80485de043efb2f370cd654f4ea44b"

    [[package]]
    name = "winapi"
    version = "0.3.9"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "5c839a674fcd7a98952e593242ea400abe93992746761e38641405d28b00f419"
    dependencies = [
     "winapi-i686-pc-windows-gnu",
     "winapi-x86_64-pc-windows-gnu",
    ]

    [[package]]
    name = "winapi-i686-pc-windows-gnu"
    version = "0.4.0"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "ac3b87c63620426dd9b991e5ce0329eff545bccbbb34f3be09ff6fb6ab51b7b6"

    [[package]]
    name = "winapi-x86_64-pc-windows-gnu"
    version = "0.4.0"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "712e227841d057c1ee1cd2fb22fa7e5a5461ae8e48fa2ca79ec42cfc1931183f"

    [[package]]
    name = "windows-link"
    version = "0.2.1"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "f0805222e57f7521d6a62e36fa9163bc891acd422f971defe97d64e70d0a4fe5"

    [[package]]
    name = "windows-sys"
    version = "0.59.0"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "1e38bc4d79ed67fd075bcc251a1c39b32a1776bbe92e5bef1f0bf1f8c531853b"
    dependencies = [
     "windows-targets",
    ]

    [[package]]
    name = "windows-sys"
    version = "0.61.2"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "ae137229bcbd6cdf0f7b80a31df61766145077ddf49416a728b02cb3921ff3fc"
    dependencies = [
     "windows-link",
    ]

    [[package]]
    name = "windows-targets"
    version = "0.52.6"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "9b724f72796e036ab90c1021d4780d4d3d648aca59e491e6b98e725b84e99973"
    dependencies = [
     "windows_aarch64_gnullvm",
     "windows_aarch64_msvc",
     "windows_i686_gnu",
     "windows_i686_gnullvm",
     "windows_i686_msvc",
     "windows_x86_64_gnu",
     "windows_x86_64_gnullvm",
     "windows_x86_64_msvc",
    ]

    [[package]]
    name = "windows_aarch64_gnullvm"
    version = "0.52.6"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "32a4622180e7a0ec044bb555404c800bc9fd9ec262ec147edd5989ccd0c02cd3"

    [[package]]
    name = "windows_aarch64_msvc"
    version = "0.52.6"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "09ec2a7bb152e2252b53fa7803150007879548bc709c039df7627cabbd05d469"

    [[package]]
    name = "windows_i686_gnu"
    version = "0.52.6"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "8e9b5ad5ab802e97eb8e295ac6720e509ee4c243f69d781394014ebfe8bbfa0b"

    [[package]]
    name = "windows_i686_gnullvm"
    version = "0.52.6"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "0eee52d38c090b3caa76c563b86c3a4bd71ef1a819287c19d586d7334ae8ed66"

    [[package]]
    name = "windows_i686_msvc"
    version = "0.52.6"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "240948bc05c5e7c6dabba28bf89d89ffce3e303022809e73deaefe4f6ec56c66"

    [[package]]
    name = "windows_x86_64_gnu"
    version = "0.52.6"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "147a5c80aabfbf0c7d901cb5895d1de30ef2907eb21fbbab29ca94c5b08b1a78"

    [[package]]
    name = "windows_x86_64_gnullvm"
    version = "0.52.6"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "24d5b23dc417412679681396f2b49f3de8c1473deb516bd34410872eff51ed0d"

    [[package]]
    name = "windows_x86_64_msvc"
    version = "0.52.6"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "589f6da84c646204747d1270a2a5661ea66ed1cced2631d546fdfb155959f9ec"
  '';

  mainRs = builtins.toFile "main.rs" ''
    mod app;
    mod memory;
    mod procs;
    mod runner;
    mod storage;
    mod sudo;
    mod theme;
    mod ui;

    use std::io;

    use app::{App, Tab};
    use crossterm::{
        event::{self, Event, KeyCode, KeyEventKind},
        execute,
        terminal::{disable_raw_mode, enable_raw_mode, EnterAlternateScreen, LeaveAlternateScreen},
    };
    use ratatui::backend::CrosstermBackend;
    use ratatui::Terminal;

    fn main() -> io::Result<()> {
        let mut stdout = io::stdout();
        enable_raw_mode()?;
        execute!(stdout, EnterAlternateScreen)?;
        let backend = CrosstermBackend::new(stdout);
        let mut terminal = Terminal::new(backend)?;

        let mut app = App::new();
        let result = run(&mut terminal, &mut app);

        disable_raw_mode()?;
        execute!(io::stdout(), LeaveAlternateScreen)?;
        terminal.show_cursor()?;
        result
    }

    fn run(terminal: &mut Terminal<CrosstermBackend<io::Stdout>>, app: &mut App) -> io::Result<()> {
        loop {
            terminal.draw(|f| ui::draw(f, app))?;
            app.refresh();

            if event::poll(std::time::Duration::from_millis(80))? {
                match event::read()? {
                    Event::Key(key) => {
                        if key.kind == KeyEventKind::Press {
                            if key.code == KeyCode::Char('r') && app.tab == Tab::Memory {
                                suspended_sudo(terminal)?;
                                app.sudo_ok = crate::sudo::have_sudo();
                                app.push_log(runner::LogLevel::Ok, "sudo credentials refreshed".into());
                            } else if app.handle_key(key.code) {
                                return Ok(());
                            }
                        }
                    }
                    Event::Resize(_, _) => {}
                    _ => {}
                }
            }
        }
    }

    /// Suspend the TUI, run sudo -v interactively, then resume.
    fn suspended_sudo(terminal: &mut Terminal<CrosstermBackend<io::Stdout>>) -> io::Result<()> {
        execute!(io::stdout(), LeaveAlternateScreen)?;
        disable_raw_mode()?;
        let _ = sudo::interactive_auth();
        enable_raw_mode()?;
        execute!(io::stdout(), EnterAlternateScreen)?;
        terminal.clear()?;
        Ok(())
    }
  '';
  appRs = builtins.toFile "app.rs" ''
    use std::collections::VecDeque;
    use std::sync::mpsc::{self, Receiver, TryRecvError};
    use std::time::{Duration, Instant};

    use crate::memory::MemInfo;
    use crate::procs::Proc;
    use crate::runner::{self, JobLog, LogLevel};
    use crate::storage::{CleanTarget, ScanState};
    use crossterm::event::KeyCode;

    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub enum Tab {
        Storage,
        Memory,
        Processes,
        Logs,
    }

    impl Tab {
        pub fn name(self) -> &'static str {
            match self {
                Tab::Storage => "Storage",
                Tab::Memory => "Memory",
                Tab::Processes => "Processes",
                Tab::Logs => "Logs",
            }
        }
    }

    const TABS: [Tab; 4] = [Tab::Storage, Tab::Memory, Tab::Processes, Tab::Logs];

    #[derive(Clone)]
    pub struct TargetRow {
        pub target: CleanTarget,
        pub selected: bool,
    }

    pub struct App {
        pub tab: Tab,
        pub targets: Vec<TargetRow>,
        pub mem: MemInfo,
        pub procs: Vec<Proc>,
        pub log: VecDeque<JobLog>,
        pub cursor: usize,
        pub proc_cursor: usize,
        /// Offset from the bottom of the log (0 = latest line visible).
        pub log_scroll: usize,
        pub scanning: bool,
        pub scan_rx: Option<Receiver<(usize, Option<u64>)>>,
        pub last_refresh: Instant,
        pub sudo_ok: bool,
    }

    impl App {
        pub fn new() -> Self {
            let home = std::env::var("HOME").unwrap_or_default();
            Self {
                tab: Tab::Storage,
                targets: crate::storage::default_targets(&home)
                    .into_iter()
                    .map(|target| TargetRow {
                        target,
                        selected: false,
                    })
                    .collect(),
                mem: MemInfo::read(),
                procs: Vec::new(),
                log: VecDeque::from([JobLog {
                    level: LogLevel::Info,
                    text: "purge ready - press s to scan".into(),
                }]),
                cursor: 0,
                proc_cursor: 0,
                log_scroll: 0,
                scanning: false,
                scan_rx: None,
                last_refresh: Instant::now(),
                sudo_ok: crate::sudo::have_sudo(),
            }
        }

        pub fn push_log(&mut self, level: LogLevel, text: String) {
            self.log.push_back(JobLog { level, text });
            if self.log.len() > 400 {
                self.log.pop_front();
            }
        }

        /// Called each frame; drains scan results and refreshes metrics.
        pub fn refresh(&mut self) {
            if let Some(rx) = &self.scan_rx {
                loop {
                    match rx.try_recv() {
                        Ok((idx, size)) => {
                            if idx < self.targets.len() {
                                self.targets[idx].target.size = size;
                                self.targets[idx].target.state = ScanState::Done;
                            }
                        }
                        Err(TryRecvError::Empty) => break,
                        Err(TryRecvError::Disconnected) => {
                            self.scanning = false;
                            self.scan_rx = None;
                            self.push_log(LogLevel::Ok, "scan complete".into());
                            break;
                        }
                    }
                }
            }

            if self.last_refresh.elapsed() > Duration::from_millis(1500) {
                self.mem = MemInfo::read();
                self.procs = crate::procs::top_processes(50);
                self.sudo_ok = crate::sudo::have_sudo();
                self.last_refresh = Instant::now();
            }

            // keep cursors in bounds as lists change size
            self.cursor = self.cursor.min(self.targets.len().saturating_sub(1));
            self.proc_cursor = self.proc_cursor.min(self.procs.len().saturating_sub(1));
        }

        pub fn start_scan(&mut self) {
            self.push_log(LogLevel::Info, "scanning targets...".into());
            self.scanning = true;
            let rows: Vec<CleanTarget> = self.targets.iter().map(|r| r.target.clone()).collect();
            let (tx, rx) = mpsc::channel();
            self.scan_rx = Some(rx);
            std::thread::spawn(move || {
                for (i, t) in rows.iter().enumerate() {
                    let size = runner::scan_target(t);
                    let _ = tx.send((i, size));
                }
            });
        }

        pub fn clean_selected(&mut self) {
            let to_clean: Vec<(String, CleanTarget)> = self
                .targets
                .iter()
                .filter(|r| r.selected)
                .map(|r| (r.target.name.to_string(), r.target.clone()))
                .collect();
            if to_clean.is_empty() {
                self.push_log(LogLevel::Warn, "no targets selected (space to select)".into());
                return;
            }
            self.push_log(
                LogLevel::Info,
                format!("cleaning {} targets...", to_clean.len()),
            );
            for (name, target) in &to_clean {
                match runner::clean_target(target) {
                    Ok((ok, msg)) => {
                        let level = if ok { LogLevel::Ok } else { LogLevel::Err };
                        self.push_log(level, format!("[{}] {}", name, msg));
                    }
                    Err(e) => self.push_log(LogLevel::Err, format!("[{}] {}", name, e)),
                }
            }
            self.start_scan();
        }

        pub fn set_all(&mut self, val: bool) {
            for row in &mut self.targets {
                row.selected = val;
            }
        }

        pub fn drop_caches(&mut self) {
            match crate::sudo::run_sudo(&["sh", "-c", "sync; echo 3 > /proc/sys/vm/drop_caches"]) {
                Ok(status) if status.success() => self.push_log(LogLevel::Ok, "dropped page cache".into()),
                Ok(_) => self.push_log(LogLevel::Err, "drop caches failed".into()),
                Err(e) => self.push_log(LogLevel::Err, format!("drop caches: {}", e)),
            }
        }

        pub fn clear_swap(&mut self) {
            let steps = [(vec!["swapoff", "-a"], "swap off"), (vec!["swapon", "-a"], "swap on")];
            for (args, label) in steps {
                let mut cmd = std::process::Command::new("sudo");
                cmd.args(["-n"]);
                cmd.args(&args);
                match cmd.output() {
                    Ok(o) if o.status.success() => self.push_log(LogLevel::Ok, label.into()),
                    Ok(_) => self.push_log(LogLevel::Err, format!("{} failed", label)),
                    Err(e) => self.push_log(LogLevel::Err, format!("{}: {}", label, e)),
                }
            }
        }

        pub fn kill_proc(&mut self, force: bool) {
            let Some(p) = self.procs.get(self.proc_cursor) else {
                return;
            };
            let sig = if force { "KILL" } else { "TERM" };
            let name = p.name.clone();
            match std::process::Command::new("kill")
                .args([format!("-{}", sig).as_str(), &p.pid.to_string()])
                .status()
            {
                Ok(_) => self.push_log(LogLevel::Ok, format!("sent {} to {}", sig, name)),
                Err(e) => self.push_log(LogLevel::Err, format!("kill {}: {}", name, e)),
            }
        }

        pub fn cycle_tab(&mut self, dir: i32) {
            let idx = TABS.iter().position(|t| *t == self.tab).unwrap_or(0) as i32;
            let n = TABS.len() as i32;
            let next = (idx + dir).rem_euclid(n) as usize;
            self.tab = TABS[next];
            self.cursor = 0;
            self.proc_cursor = 0;
            self.log_scroll = 0;
        }

        pub fn handle_key(&mut self, key: KeyCode) -> bool {
            match self.tab {
                Tab::Storage => self.handle_storage_key(key),
                Tab::Memory => self.handle_memory_key(key),
                Tab::Processes => self.handle_proc_key(key),
                Tab::Logs => self.handle_logs_key(key),
            }
        }

        fn handle_storage_key(&mut self, key: KeyCode) -> bool {
            match key {
                KeyCode::Char('q') => true,
                KeyCode::Tab => {
                    self.cycle_tab(1);
                    false
                }
                KeyCode::BackTab => {
                    self.cycle_tab(-1);
                    false
                }
                KeyCode::Down | KeyCode::Char('j') => {
                    self.cursor = (self.cursor + 1).min(self.targets.len().saturating_sub(1));
                    false
                }
                KeyCode::Up | KeyCode::Char('k') => {
                    self.cursor = self.cursor.saturating_sub(1);
                    false
                }
                KeyCode::PageDown => {
                    self.cursor = (self.cursor + 10).min(self.targets.len().saturating_sub(1));
                    false
                }
                KeyCode::PageUp => {
                    self.cursor = self.cursor.saturating_sub(10);
                    false
                }
                KeyCode::Home => {
                    self.cursor = 0;
                    false
                }
                KeyCode::End => {
                    self.cursor = self.targets.len().saturating_sub(1);
                    false
                }
                KeyCode::Char(' ') => {
                    if let Some(row) = self.targets.get_mut(self.cursor) {
                        row.selected = !row.selected;
                    }
                    false
                }
                KeyCode::Char('s') => {
                    self.start_scan();
                    false
                }
                KeyCode::Char('c') => {
                    self.clean_selected();
                    false
                }
                KeyCode::Char('a') => {
                    self.set_all(true);
                    false
                }
                KeyCode::Char('n') => {
                    self.set_all(false);
                    false
                }
                _ => false,
            }
        }

        fn handle_memory_key(&mut self, key: KeyCode) -> bool {
            match key {
                KeyCode::Char('q') => true,
                KeyCode::Tab => {
                    self.cycle_tab(1);
                    false
                }
                KeyCode::BackTab => {
                    self.cycle_tab(-1);
                    false
                }
                KeyCode::Char('d') => {
                    self.drop_caches();
                    false
                }
                KeyCode::Char('w') => {
                    self.clear_swap();
                    false
                }
                KeyCode::Char('r') => {
                    // sudo re-auth is handled by main loop w/ terminal suspend
                    false
                }
                _ => false,
            }
        }

        fn handle_proc_key(&mut self, key: KeyCode) -> bool {
            match key {
                KeyCode::Char('q') => true,
                KeyCode::Tab => {
                    self.cycle_tab(1);
                    false
                }
                KeyCode::BackTab => {
                    self.cycle_tab(-1);
                    false
                }
                KeyCode::Down | KeyCode::Char('j') => {
                    self.proc_cursor = (self.proc_cursor + 1).min(self.procs.len().saturating_sub(1));
                    false
                }
                KeyCode::Up | KeyCode::Char('k') => {
                    self.proc_cursor = self.proc_cursor.saturating_sub(1);
                    false
                }
                KeyCode::PageDown => {
                    self.proc_cursor = (self.proc_cursor + 10).min(self.procs.len().saturating_sub(1));
                    false
                }
                KeyCode::PageUp => {
                    self.proc_cursor = self.proc_cursor.saturating_sub(10);
                    false
                }
                KeyCode::Home => {
                    self.proc_cursor = 0;
                    false
                }
                KeyCode::End => {
                    self.proc_cursor = self.procs.len().saturating_sub(1);
                    false
                }
                KeyCode::Char('x') => {
                    self.kill_proc(false);
                    false
                }
                KeyCode::Char('X') => {
                    self.kill_proc(true);
                    false
                }
                _ => false,
            }
        }

        fn handle_logs_key(&mut self, key: KeyCode) -> bool {
            match key {
                KeyCode::Char('q') => true,
                KeyCode::Tab => {
                    self.cycle_tab(1);
                    false
                }
                KeyCode::BackTab => {
                    self.cycle_tab(-1);
                    false
                }
                KeyCode::Char('c') => {
                    self.log.clear();
                    self.log_scroll = 0;
                    false
                }
                KeyCode::Down | KeyCode::Char('j') => {
                    self.log_scroll = self.log_scroll.saturating_sub(1);
                    false
                }
                KeyCode::Up | KeyCode::Char('k') => {
                    self.log_scroll = self.log_scroll.saturating_add(1).min(self.log.len());
                    false
                }
                KeyCode::PageDown => {
                    self.log_scroll = self.log_scroll.saturating_sub(10);
                    false
                }
                KeyCode::PageUp => {
                    self.log_scroll = self.log_scroll.saturating_add(10).min(self.log.len());
                    false
                }
                KeyCode::Home => {
                    self.log_scroll = self.log.len();
                    false
                }
                KeyCode::End => {
                    self.log_scroll = 0;
                    false
                }
                _ => false,
            }
        }
    }

    impl Default for App {
        fn default() -> Self {
            Self::new()
        }
    }

    pub fn display_bytes(bytes: u64) -> String {
        runner::display_size(bytes)
    }

    pub fn tab_list() -> &'static [Tab] {
        &TABS
    }
  '';
  uiRs = builtins.toFile "ui.rs" ''
    use ratatui::{
        layout::{Constraint, Layout, Rect},
        style::{Modifier, Style},
        text::{Line, Span},
        widgets::{Block, Borders, Cell, Gauge, Paragraph, Row, Table},
        Frame,
    };

    use crate::app::{display_bytes, App, Tab};
    use crate::runner::LogLevel;
    use crate::storage::ScanState;
    use crate::theme;

    fn header(f: &mut Frame, app: &App) {
        let area = f.area();
        let chunk = Layout::vertical([
            Constraint::Length(3),
            Constraint::Length(1),
            Constraint::Min(0),
            Constraint::Length(3),
        ])
        .split(area);

        let tabs: Vec<Line> = crate::app::tab_list()
            .iter()
            .map(|t| {
                let name = t.name();
                if *t == app.tab {
                    Line::from(vec![
                        Span::styled("◆ ", theme::accent()),
                        Span::styled(name, theme::accent_bold()),
                    ])
                } else {
                    Line::from(vec![
                        Span::styled("◇ ", theme::subtle()),
                        Span::styled(name, theme::text()),
                    ])
                }
            })
            .collect();
        let title = Paragraph::new(tabs)
            .block(Block::default().borders(Borders::ALL).border_style(theme::subtle()))
            .style(theme::text());
        f.render_widget(title, chunk[0]);

        // status line
        let mem = &app.mem;
        let status = format!(
            "RAM {} / {}   Swap {} / {}   Reclaimable {}",
            display_bytes(mem.used_kb() * 1024),
            display_bytes(mem.total_kb * 1024),
            display_bytes(mem.swap_used_kb() * 1024),
            display_bytes(mem.swap_total_kb * 1024),
            display_bytes(mem.reclaimable_kb() * 1024),
        );
        f.render_widget(
            Paragraph::new(Line::from(Span::styled(status, theme::subtle())))
                .style(theme::text()),
            chunk[1],
        );

        // body
        match app.tab {
            Tab::Storage => draw_storage(f, app, chunk[2]),
            Tab::Memory => draw_memory(f, app, chunk[2]),
            Tab::Processes => draw_processes(f, app, chunk[2]),
            Tab::Logs => draw_logs(f, app, chunk[2]),
        }

        // footer hints
        let hint = match app.tab {
            Tab::Storage => "s scan  space select  a/n all/none  c clean  ↑/↓ move  PgUp/PgDn =10  Home/End  q quit",
            Tab::Memory => "d drop caches  w clear swap  r re-auth sudo  q quit",
            Tab::Processes => "↑/↓ move  x SIGTERM  X SIGKILL  PgUp/PgDn  Home/End  q quit",
            Tab::Logs => "↑/↓ scroll  PgUp/PgDn  c clear log  q quit",
        };
        f.render_widget(
            Paragraph::new(Line::from(Span::styled(hint, theme::subtle())))
                .style(theme::text()),
            chunk[3],
        );
    }

    fn draw_storage(f: &mut Frame, app: &App, area: Rect) {
        let widths = [
            Constraint::Length(3),
            Constraint::Length(26),
            Constraint::Length(12),
            Constraint::Min(10),
        ];
        // account for block borders (2) + header row (1)
        let (top, bottom) = window(app.targets.len(), app.cursor, area.height.saturating_sub(3) as usize);

        let rows: Vec<Row> = app
            .targets
            .iter()
            .enumerate()
            .skip(top)
            .take(bottom.saturating_sub(top))
            .map(|(i, row)| {
                let t = &row.target;
                let mark = if row.selected { "[x]" } else { "[ ]" };
                let size = match (t.state, t.size) {
                    (ScanState::Scanning, _) => "…".to_string(),
                    (ScanState::Pending, _) => "-".to_string(),
                    (_, Some(sz)) => display_bytes(sz),
                    (_, None) => "?".to_string(),
                };
                let style = if i == app.cursor {
                    Style::default()
                        .bg(theme::SURFACE)
                        .add_modifier(Modifier::BOLD)
                } else {
                    Style::default()
                };
                let fg = if i == app.cursor {
                    theme::MAUVE
                } else if row.selected {
                    theme::GREEN
                } else {
                    theme::TEXT
                };
                Row::new(vec![
                    Cell::from(mark),
                    Cell::from(t.name).style(Style::default().fg(fg)),
                    Cell::from(size).style(Style::default().fg(theme::PEACH)),
                    Cell::from(t.desc).style(Style::default().fg(theme::SUBTLE)),
                ])
                .style(style)
            })
            .collect();

        let title = scroll_title("Storage", top, bottom, app.targets.len());
        let table = Table::new(rows, widths)
            .header(Row::new(vec![
                Cell::from("sel"),
                Cell::from("target"),
                Cell::from("size"),
                Cell::from("description"),
            ]))
            .block(Block::default().borders(Borders::ALL).title(title));
        f.render_widget(table, area);
    }

    /// Build a table title with a scroll position indicator when overflowing.
    fn scroll_title(base: &str, top: usize, bottom: usize, total: usize) -> String {
        if total <= bottom.saturating_sub(top) || total == 0 {
            base.to_string()
        } else {
            format!("{}  {}/{}", base, bottom, total)
        }
    }

    /// Compute the visible slice [top, bottom) for a list given the selected
    /// cursor, keeping `cursor` on-screen. `visible` is the max rows we can show.
    fn window(total: usize, cursor: usize, visible: usize) -> (usize, usize) {
        if total == 0 || visible == 0 {
            return (0, 0);
        }
        let cursor = cursor.min(total.saturating_sub(1));
        if total <= visible {
            return (0, total);
        }
        let top = cursor
            .saturating_sub(visible - 1)
            .min(total.saturating_sub(visible));
        (top, top + visible)
    }

    fn draw_memory(f: &mut Frame, app: &App, area: Rect) {
        let m = &app.mem;
        let inner = Layout::vertical([
            Constraint::Length(3),
            Constraint::Length(3),
            Constraint::Length(3),
            Constraint::Length(1),
            Constraint::Min(4),
        ])
        .split(area);

        let ram_ratio = m.ratio(m.used_kb());
        let swap_ratio = m.swap_ratio();
        let reclaim_ratio = m.ratio(m.reclaimable_kb());

        let ram_gauge = Gauge::default()
            .block(Block::default().borders(Borders::ALL).title("RAM"))
            .gauge_style(Style::default().fg(theme::MAUVE))
            .ratio(ram_ratio)
            .label(format!(
                "{} / {}  ({}%)",
                display_bytes(m.used_kb() * 1024),
                display_bytes(m.total_kb * 1024),
                (ram_ratio * 100.0) as u64
            ));
        let swap_gauge = Gauge::default()
            .block(Block::default().borders(Borders::ALL).title("Swap"))
            .gauge_style(Style::default().fg(theme::BLUE))
            .ratio(swap_ratio)
            .label(format!(
                "{} / {}",
                display_bytes(m.swap_used_kb() * 1024),
                display_bytes(m.swap_total_kb * 1024)
            ));
        let reclaim_gauge = Gauge::default()
            .block(Block::default().borders(Borders::ALL).title("Reclaimable (page cache)"))
            .gauge_style(Style::default().fg(theme::GREEN))
            .ratio(reclaim_ratio)
            .label(format!(
                "{}  ({}%)",
                display_bytes(m.reclaimable_kb() * 1024),
                (reclaim_ratio * 100.0) as u64
            ));

        f.render_widget(ram_gauge, inner[0]);
        f.render_widget(swap_gauge, inner[1]);
        f.render_widget(reclaim_gauge, inner[2]);

        let info = if app.sudo_ok {
            "sudo: cached ✓".to_string()
        } else {
            "sudo: not cached (press r to authenticate)".to_string()
        };
        f.render_widget(
            Paragraph::new(Line::from(Span::styled(info, theme::subtle()))),
            inner[3],
        );

        // buff/cache breakdown
        let detail = format!(
            "buffers {}   cached {}   slab_reclaimable {}",
            display_bytes(m.buffers_kb * 1024),
            display_bytes(m.cached_kb * 1024),
            display_bytes(m.sreclaimable_kb * 1024),
        );
        f.render_widget(
            Paragraph::new(Line::from(Span::styled(detail, theme::text())))
                .block(Block::default().borders(Borders::ALL).title("Detail")),
            inner[4],
        );
    }

    fn draw_processes(f: &mut Frame, app: &App, area: Rect) {
        let widths = [
            Constraint::Length(8),
            Constraint::Length(28),
            Constraint::Length(12),
            Constraint::Min(20),
        ];
        let (top, bottom) = window(app.procs.len(), app.proc_cursor, area.height.saturating_sub(3) as usize);

        let rows: Vec<Row> = app
            .procs
            .iter()
            .enumerate()
            .skip(top)
            .take(bottom.saturating_sub(top))
            .map(|(i, p)| {
                let style = if i == app.proc_cursor {
                    Style::default()
                        .bg(theme::SURFACE)
                        .add_modifier(Modifier::BOLD)
                } else {
                    Style::default()
                };
                let fg = if i == app.proc_cursor {
                    theme::RED
                } else {
                    theme::TEXT
                };
                Row::new(vec![
                    Cell::from(p.pid.to_string()).style(Style::default().fg(theme::SUBTLE)),
                    Cell::from(p.name.as_str()).style(Style::default().fg(fg)),
                    Cell::from(display_bytes(p.rss_kb * 1024)).style(Style::default().fg(theme::PEACH)),
                    Cell::from(p.cmd.as_str()).style(Style::default().fg(theme::SUBTLE)),
                ])
                .style(style)
            })
            .collect();

        let title = scroll_title("Top processes by RAM", top, bottom, app.procs.len());
        let table = Table::new(rows, widths)
            .header(Row::new(vec![
                Cell::from("pid"),
                Cell::from("name"),
                Cell::from("rss"),
                Cell::from("cmdline"),
            ]))
            .block(Block::default().borders(Borders::ALL).title(title));
        f.render_widget(table, area);
    }

    fn draw_logs(f: &mut Frame, app: &App, area: Rect) {
        let visible = area.height.saturating_sub(2) as usize;
        let total = app.log.len();

        // log_scroll = offset from the bottom (0 = latest visible). Slice accordingly.
        let scroll = app.log_scroll.min(total);
        let shown = visible.min(total - scroll);

        let start = if shown == 0 { total } else { total - scroll - shown };

        let lines: Vec<Line> = app
            .log
            .iter()
            .skip(start)
            .take(shown.max(1))
            .map(|entry| {
                let color = match entry.level {
                    LogLevel::Ok => theme::GREEN,
                    LogLevel::Err => theme::RED,
                    LogLevel::Warn => theme::YELLOW,
                    LogLevel::Info => theme::TEXT,
                };
                Line::from(Span::styled(entry.text.as_str(), Style::default().fg(color)))
            })
            .collect();
        let title = if scroll == 0 {
            "Log".to_string()
        } else {
            format!("Log  ({} above)", scroll)
        };
        f.render_widget(
            Paragraph::new(lines)
                .block(Block::default().borders(Borders::ALL).title(title))
                .style(theme::text()),
            area,
        );
    }

    pub fn draw(f: &mut Frame, app: &App) {
        f.render_widget(
            Block::default().style(Style::default().bg(theme::BG)),
            f.area(),
        );
        header(f, app);
    }
  '';
  themeRs = builtins.toFile "theme.rs" ''
    use ratatui::style::{Color, Style};

    pub const BG: Color = Color::Rgb(30, 30, 46);      // base
    pub const SURFACE: Color = Color::Rgb(24, 24, 37); // mantle
    pub const TEXT: Color = Color::Rgb(205, 214, 244); // text
    pub const SUBTLE: Color = Color::Rgb(166, 173, 200); // subtitle0
    pub const LAVENDER: Color = Color::Rgb(180, 190, 254); // lavender
    pub const MAUVE: Color = Color::Rgb(203, 166, 247); // mauve
    pub const GREEN: Color = Color::Rgb(166, 227, 161); // green
    pub const YELLOW: Color = Color::Rgb(249, 226, 175); // yellow
    pub const RED: Color = Color::Rgb(243, 139, 168); // red
    pub const PEACH: Color = Color::Rgb(250, 179, 135); // peach
    pub const BLUE: Color = Color::Rgb(137, 180, 250); // blue

    pub fn text() -> Style {
        Style::default().fg(TEXT)
    }
    pub fn text_bold() -> Style {
        Style::default().fg(TEXT).add_modifier(ratatui::style::Modifier::BOLD)
    }
    pub fn subtle() -> Style {
        Style::default().fg(SUBTLE)
    }
    pub fn accent() -> Style {
        Style::default().fg(MAUVE)
    }
    pub fn accent_bold() -> Style {
        Style::default().fg(MAUVE).add_modifier(ratatui::style::Modifier::BOLD)
    }
  '';
  memoryRs = builtins.toFile "memory.rs" ''
    use std::fs;

    #[derive(Debug, Clone, Copy, Default)]
    pub struct MemInfo {
        pub total_kb: u64,
        pub free_kb: u64,
        pub available_kb: u64,
        pub buffers_kb: u64,
        pub cached_kb: u64,
        pub sreclaimable_kb: u64,
        pub swap_total_kb: u64,
        pub swap_free_kb: u64,
    }

    impl MemInfo {
        pub fn read() -> MemInfo {
            let mut m = MemInfo::default();
            if let Ok(data) = fs::read_to_string("/proc/meminfo") {
                for line in data.lines() {
                    let mut it = line.split_whitespace();
                    let key = it.next().unwrap_or("").trim_end_matches(':');
                    let val: u64 = it.next().and_then(|s| s.parse().ok()).unwrap_or(0);
                    match key {
                        "MemTotal" => m.total_kb = val,
                        "MemFree" => m.free_kb = val,
                        "MemAvailable" => m.available_kb = val,
                        "Buffers" => m.buffers_kb = val,
                        "Cached" => m.cached_kb = val,
                        "SReclaimable" => m.sreclaimable_kb = val,
                        "SwapTotal" => m.swap_total_kb = val,
                        "SwapFree" => m.swap_free_kb = val,
                        _ => {}
                    }
                }
            }
            m
        }

        /// Memory that is technically "used" but reclaimable (page cache).
        pub fn reclaimable_kb(&self) -> u64 {
            self.cached_kb + self.sreclaimable_kb
        }

        /// What drop-caches-style reclaim could target (cached + reclaimable slab).
        pub fn droppable_kb(&self) -> u64 {
            self.reclaimable_kb()
        }

        pub fn used_kb(&self) -> u64 {
            self.total_kb.saturating_sub(self.available_kb)
        }

        pub fn swap_used_kb(&self) -> u64 {
            self.swap_total_kb.saturating_sub(self.swap_free_kb)
        }

        pub fn ratio(&self, used: u64) -> f64 {
            if self.total_kb == 0 {
                0.0
            } else {
                used as f64 / self.total_kb as f64
            }
        }

        pub fn swap_ratio(&self) -> f64 {
            if self.swap_total_kb == 0 {
                0.0
            } else {
                self.swap_used_kb() as f64 / self.swap_total_kb as f64
            }
        }
    }

    pub fn drop_caches_needs_root() -> bool {
        true
    }
  '';
  procsRs = builtins.toFile "procs.rs" ''
    use std::fs;

    #[derive(Debug, Clone)]
    pub struct Proc {
        pub pid: i64,
        pub name: String,
        pub rss_kb: u64,
        pub cmd: String,
    }

    /// List running processes sorted by RSS (descending), top `limit`.
    pub fn top_processes(limit: usize) -> Vec<Proc> {
        let mut procs = Vec::new();
        if let Ok(entries) = fs::read_dir("/proc") {
            for e in entries.flatten() {
                let name = e.file_name();
                let pid = match name.to_str().and_then(|s| s.parse::<i64>().ok()) {
                    Some(p) => p,
                    None => continue,
                };
                let status_path = format!("/proc/{}/status", pid);
                let comm_path = format!("/proc/{}/comm", pid);
                let (rss, _statname) = read_status(&status_path);
                let cmdline = fs::read_to_string(format!("/proc/{}/cmdline", pid))
                    .unwrap_or_default()
                    .replace('\0', " ");
                let comm = match fs::read_to_string(&comm_path) {
                    Ok(c) => c.trim().to_string(),
                    Err(_) => continue,
                };
                procs.push(Proc {
                    pid,
                    rss_kb: rss,
                    name: comm_label(&comm),
                    cmd: cmdline.trim().to_string(),
                });
            }
        }
        procs.sort_by(|a, b| b.rss_kb.cmp(&a.rss_kb));
        procs.truncate(limit);
        procs
    }

    fn read_status(path: &str) -> (u64, String) {
        let data = match fs::read_to_string(path) {
            Ok(d) => d,
            Err(_) => return (0, String::new()),
        };
        let mut rss = 0u64;
        let mut name = String::new();
        for line in data.lines() {
            let mut it = line.splitn(2, ':');
            let key = it.next().unwrap_or("").trim();
            let val = it.next().unwrap_or("").trim();
            match key {
                "Name" => name = val.to_string(),
                "VmRSS" => {
                    rss = val
                        .split_whitespace()
                        .next()
                        .and_then(|s| s.parse().ok())
                        .unwrap_or(0)
                }
                _ => {}
            }
        }
        (rss, name)
    }

    fn comm_label(comm: &str) -> String {
        let body = comm.trim_matches(|c| c == '[' || c == ']');
        if body.len() > 24 {
            body.chars().take(21).collect::<String>() + "..."
        } else {
            body.to_string()
        }
    }
  '';
  storageRs = builtins.toFile "storage.rs" ''
    use std::process::Command;

    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub enum CleanKind {
        Tool,
        EmptyDir,
        RemDir,
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
    pub enum ScanState {
        #[default]
        Pending,
        Scanning,
        Done,
        Missing,
    }

    #[derive(Debug, Clone)]
    pub struct CleanTarget {
        pub name: &'static str,
        pub desc: &'static str,
        pub kind: CleanKind,
        pub cmd: Vec<String>,
        pub needs_root: bool,
        pub size: Option<u64>,
        pub state: ScanState,
    }

    impl CleanTarget {
        pub fn can_clean(&self) -> bool {
            self.size.unwrap_or(0) > 0
        }
    }

    /// Compute directory size in bytes (`du -sb`).
    pub fn dir_size(path: &str) -> Option<u64> {
        let out = Command::new("du").args(["-sb", path]).output().ok()?;
        if !out.status.success() {
            return None;
        }
        let line = String::from_utf8_lossy(&out.stdout);
        let bytes: u64 = line.split_whitespace().next()?.parse().ok()?;
        Some(bytes)
    }

    /// Empty a directory's contents, keeping the directory itself.
    pub fn empty_dir(path: &str) -> Result<String, String> {
        let out = Command::new("find")
            .arg(path)
            .arg("-mindepth")
            .arg("1")
            .args(["-delete"])
            .output()
            .map_err(|e| e.to_string())?;
        if out.status.success() {
            Ok(String::from_utf8_lossy(&out.stderr).trim().to_string())
        } else {
            Err(String::from_utf8_lossy(&out.stderr).trim().to_string())
        }
    }

    /// Remove an entire directory tree.
    pub fn rm_dir(path: &str) -> Result<(), String> {
        let out = Command::new("rm")
            .args(["-rf", "--", path])
            .output()
            .map_err(|e| e.to_string())?;
        if out.status.success() {
            Ok(())
        } else {
            Err(String::from_utf8_lossy(&out.stderr).trim().to_string())
        }
    }

    /// Default set of cleanup targets.
    pub fn default_targets(home: &str) -> Vec<CleanTarget> {
        let hm_profile = format!("{}/.local/state/nix/profiles/profile", home);
        let caches: Vec<(&'static str, &'static str)> = vec![
            ("nix", "flake/fetcher cache metadata"),
            ("go-build", "Go build cache"),
            ("wine", "Wine renderer shader cache"),
            ("kdenlive", "Kdenlive media cache"),
            ("thumbnails", "File manager thumbnails"),
            ("appimage-run", "Extracted AppImage mounts"),
            ("webapps", "Web app (instagram/notebooklm) cache"),
            ("cliphist", "Clipboard history DB"),
            ("mesa_shader_cache", "Mesa shader cache"),
        ];

        let mut t: Vec<CleanTarget> = Vec::new();

        t.push(CleanTarget {
            name: "Nix store GC",
            desc: "nix-store --gc  (frees dead store paths)",
            kind: CleanKind::Tool,
            cmd: vec!["nix-store".into(), "--gc".into()],
            needs_root: false,
            size: None,
            state: ScanState::Pending,
        });

        t.push(CleanTarget {
            name: "Nix store optimise",
            desc: "nix-store --optimise  (dedupe hard links)",
            kind: CleanKind::Tool,
            cmd: vec!["nix-store".into(), "--optimise".into()],
            needs_root: false,
            size: None,
            state: ScanState::Pending,
        });

        t.push(CleanTarget {
            name: "Home-manager generations",
            desc: "delete generations older than 7d",
            kind: CleanKind::Tool,
            cmd: vec![
                "nix-env".into(),
                "-p".into(),
                hm_profile,
                "--delete-generations".into(),
                "7d".into(),
            ],
            needs_root: false,
            size: None,
            state: ScanState::Pending,
        });

        t.push(CleanTarget {
            name: "Systemd journal",
            desc: "journalctl --vacuum-size=100M (root)",
            kind: CleanKind::Tool,
            cmd: vec!["journalctl".into(), "--vacuum-size=100M".into()],
            needs_root: true,
            size: None,
            state: ScanState::Pending,
        });

        for (name, desc) in caches {
            let path = format!("{}/.cache/{}", home, name);
            t.push(CleanTarget {
                name,
                desc,
                kind: CleanKind::EmptyDir,
                cmd: vec![path],
                needs_root: false,
                size: None,
                state: ScanState::Pending,
            });
        }

        t.push(CleanTarget {
            name: "npm cache",
            desc: "npm cache clean --force",
            kind: CleanKind::Tool,
            cmd: vec!["npm".into(), "cache".into(), "clean".into(), "--force".into()],
            needs_root: false,
            size: None,
            state: ScanState::Pending,
        });

        t.push(CleanTarget {
            name: "Trash",
            desc: "empty ~/.local/share/Trash",
            kind: CleanKind::EmptyDir,
            cmd: vec![format!("{}/.local/share/Trash", home)],
            needs_root: false,
            size: None,
            state: ScanState::Pending,
        });

        t
    }
  '';
  runnerRs = builtins.toFile "runner.rs" ''
    use std::process::Command;

    use crate::storage::{CleanKind, CleanTarget};

    #[derive(Debug, Clone)]
    pub enum LogLevel {
        Info,
        Ok,
        Warn,
        Err,
    }

    #[derive(Debug, Clone)]
    pub struct JobLog {
        pub level: LogLevel,
        pub text: String,
    }

    pub fn display_size(bytes: u64) -> String {
        const UNITS: [&str; 6] = ["B", "KiB", "MiB", "GiB", "TiB", "PiB"];
        if bytes == 0 {
            return "0 B".to_string();
        }
        let mut v = bytes as f64;
        let mut i = 0;
        while v >= 1024.0 && i < UNITS.len() - 1 {
            v /= 1024.0;
            i += 1;
        }
        if i == 0 {
            format!("{} {}", bytes, UNITS[i])
        } else {
            format!("{:.1} {}", v, UNITS[i])
        }
    }

    fn expand(p: &str) -> String {
        let home = std::env::var("HOME").unwrap_or_default();
        p.replace("~", &home)
    }

    /// Scan a target's size in bytes (if it is a directory target).
    pub fn scan_target(t: &CleanTarget) -> Option<u64> {
        match t.kind {
            CleanKind::EmptyDir | CleanKind::RemDir => {
                let path = expand(t.cmd.get(0)?);
                crate::storage::dir_size(&path)
            }
            CleanKind::Tool => None,
        }
    }

    /// Execute a single cleanup action for a target. Returns (ok, message).
    pub fn clean_target(t: &CleanTarget) -> Result<(bool, String), String> {
        match t.kind {
            CleanKind::EmptyDir => {
                let path = expand(t.cmd.get(0).ok_or("no path")?);
                let (ok, msg) = run_owned("find", &[&path, "-mindepth", "1", "-delete"], t.needs_root)?;
                Ok((ok, msg))
            }
            CleanKind::RemDir => {
                let path = expand(t.cmd.get(0).ok_or("no path")?);
                let (ok, msg) = run_owned("rm", &["-rf", "--", &path], false)?;
                Ok((ok, msg))
            }
            CleanKind::Tool => {
                let bin = t.cmd.get(0).cloned().unwrap_or_default();
                let args: Vec<String> = t.cmd.get(1..).unwrap_or(&[]).to_vec();
                let arg_refs: Vec<&str> = args.iter().map(|s| s.as_str()).collect();
                let (ok, msg) = run_owned(&bin, &arg_refs, t.needs_root)?;
                Ok((ok, msg))
            }
        }
    }

    fn run_owned(bin: &str, args: &[&str], needs_root: bool) -> Result<(bool, String), String> {
        if needs_root && !crate::sudo::have_sudo() {
            return Err("sudo auth needed - press r to cache".into());
        }
        let pretty = if needs_root {
            format!("sudo -n {} {}", bin, args.join(" "))
        } else {
            format!("{} {}", bin, args.join(" "))
        };

        let mut cmd = Command::new(if needs_root { "sudo" } else { bin });
        if needs_root {
            cmd.args(["-n", bin]);
        }
        cmd.args(args);

        let out = cmd.output().map_err(|e| e.to_string())?;
        let ok = out.status.success();
        let stderr = String::from_utf8_lossy(&out.stderr).trim().to_string();
        let stdout = String::from_utf8_lossy(&out.stdout).trim().to_string();
        let tail = if !stderr.is_empty() {
            stderr
        } else {
            let s: String = stdout.chars().take(200).collect();
            if !s.is_empty() { s } else { String::new() }
        };

        Ok((ok, if tail.is_empty() { pretty } else { format!("{} => {}", pretty, tail) }))
    }
  '';
  sudoRs = builtins.toFile "sudo.rs" ''
    use std::process::{Command, Stdio};

    /// Interactively refresh sudo credentials. Must be called with the
    /// terminal in a state that can show the password prompt (raw mode off).
    pub fn interactive_auth() {
        let _ = Command::new("sudo").arg("-v").status();
    }

    /// Check whether sudo credentials are already cached (non-interactive).
    pub fn have_sudo() -> bool {
        Command::new("sudo")
            .args(["-n", "true"])
            .stdin(Stdio::null())
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .status()
            .map(|s| s.success())
            .unwrap_or(false)
    }

    /// Run a command with cached sudo credentials. Fails if not authenticated.
    pub fn run_sudo(args: &[&str]) -> Result<std::process::ExitStatus, String> {
        Command::new("sudo")
            .args(["-n"])
            .args(args)
            .output()
            .map(|o| o.status)
            .map_err(|e| e.to_string())
    }

    pub fn run_cmd(args: &[&str]) -> Result<std::process::ExitStatus, String> {
        Command::new(args[0])
            .args(&args[1..])
            .output()
            .map(|o| o.status)
            .map_err(|e| e.to_string())
    }
  '';
in
rustPlatform.buildRustPackage {
  pname = "purge";
  version = "0.1.0";
  src = stdenv.mkDerivation {
    pname = "purge-crate-src";
    version = "0.1.0";
    buildCommand = ''
      mkdir -p $out/src
      cp ${mainRs} $out/src/main.rs
      cp ${appRs} $out/src/app.rs
      cp ${uiRs} $out/src/ui.rs
      cp ${themeRs} $out/src/theme.rs
      cp ${memoryRs} $out/src/memory.rs
      cp ${procsRs} $out/src/procs.rs
      cp ${storageRs} $out/src/storage.rs
      cp ${runnerRs} $out/src/runner.rs
      cp ${sudoRs} $out/src/sudo.rs
      cp ${cargoToml} $out/Cargo.toml
      cp ${cargoLock} $out/Cargo.lock
    '';
  };
  cargoLock.lockFile = cargoLock;
  nativeBuildInputs = [ makeWrapper ];
  postInstall = ''
    wrapProgram $out/bin/purge \
      --prefix PATH : "${lib.makeBinPath [ nodejs ]}"
  '';
  meta = {
    description = "Catppuccin-themed RAM and storage cleaning TUI for NixOS";
    license = lib.licenses.mit;
    mainProgram = "purge";
  };
}
