{ config, pkgs, ... }: {

  xdg.configFile."kitty/kitty.conf".text = ''
    font_family JetBrainsMono Nerd Font
    font_size 12
    bold_font auto
    italic_font auto
    bold_italic_font auto

    background_opacity 0.85
    background_blur 2
    window_padding_width 12
    hide_window_decorations yes
    confirm_os_window_close 0

    # Catppuccin Mocha colors
    foreground #cdd6f4
    background #1e1e2e
    selection_foreground #1e1e2e
    selection_background #cba6f7

    url_color #89b4fa

    # Black
    color0 #45475a
    color8 #585b70

    # Red
    color1 #f38ba8
    color9 #f38ba8

    # Green
    color2 #a6e3a1
    color10 #a6e3a1

    # Yellow
    color3 #f9e2af
    color11 #f9e2af

    # Blue
    color4 #89b4fa
    color12 #89b4fa

    # Magenta
    color5 #cba6f7
    color13 #cba6f7

    # Cyan
    color6 #94e2d5
    color14 #94e2d5

    # White
    color7 #bac2de
    color15 #a6adc8

    cursor #f5e0dc
    cursor_text_color #1e1e2e
    tab_bar_style powerline
    active_tab_foreground #1e1e2e
    active_tab_background #cba6f7
    inactive_tab_foreground #cdd6f4
    inactive_tab_background #313244
    tab_bar_margin_width 4

    # Matugen dynamic colors (generated by `matugen image ...`)
    include /home/veer/.config/matugen/kitty-colors.conf
  '';

}
